# CloudMan settings
cm_cluster_type: "{{ lookup('env', 'CM_CLUSTER_TYPE') | default('KUBE_RKE', true) }}"
cm_initial_cluster_data: "{{ lookup('env', 'CM_INITIAL_CLUSTER_DATA') | b64decode | from_yaml }}"
cm_initial_storage_size: "{{ lookup('env', 'CM_INITIAL_STORAGE_SIZE') }}"
cm_helm_values: "{{ lookup('env', 'CM_HELM_VALUES') | b64decode | from_yaml }}"
cm_skip_cloudman: "{{ lookup('env', 'CM_SKIP_CLOUDMAN') | default('false', true) }}"
cm_cluster_name: local
cm_namespace_name: "{{ lookup('env', 'CM_NAMESPACE_NAME') | default('cloudman', true) }}"
cm_chart_version: "{{ lookup('env', 'CM_CHART_VERSION') | default('', true) }}"
cm_charts_repo: "{{ lookup('env', 'CM_CHARTS_REPO') | default('https://raw.githubusercontent.com/cloudve/helm-charts/master/', true) }}"
cm_deployment_name: "{{ lookup('env', 'CM_DEPLOYMENT_NAME') }}"
cm_skip_wait_till_ready: true
cm_force_pull_images: false
cm_validate_certs: "{{ lookup('env', 'CM_VALIDATE_CERTS') | default('no', true) }}"

# cluster settings
cluster_hostname: "{{ lookup('env', 'CLUSTER_HOSTNAME') | default(inventory_hostname, true) }}"
cluster_password: "{{ lookup('env', 'CLUSTER_PASSWORD') }}"

# rancher settings
rancher_hostname: "rancher.{{ cluster_hostname }}{% if cluster_hostname | ipaddr %}.xip.io{% endif %}"

# Keycloak operator
cm_keycloak_operator_version: "{{ lookup('env', 'CM_KEYCLOAK_OPERATOR_VERSION') | default('latest', true) }}"
cm_keycloak_operator_path: "{{ lookup('env', 'CM_KEYCLOAK_OPERATOR_PATH') | default('/tmp/keycloak-operator-{{ cm_keycloak_operator_version }}', true) }}"
cm_keycloak_namespace: "{{ lookup('env', 'CM_KEYCLOAK_NAMESPACE') | default('keycloak', true) }}"
cm_keycloak_operator_fork: "{{ lookup('env', 'CM_KEYCLOAK_OPERATOR_FORK') | default('keycloak/keycloak-operator', true) }}"
cm_keycloak_realm_name: "{{ lookup('env', 'CM_KEYCLOAK_REALM_NAME') | default('gvl', true) }}"
cm_keycloak_realm_registration: "{{ lookup('env', 'CM_KEYCLOAK_REALM_REGISTRATION') | default('false', true) }}"
keycloak_hostname: "auth.{{ cluster_hostname }}{% if cluster_hostname | ipaddr %}.xip.io{% endif %}"

# cloud provider for this cluster:
# ref: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/
# ref: https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/
kube_cloud_provider: "{{ lookup('env', 'KUBE_CLOUD_PROVIDER') }}"
kube_cloud_conf: "{{ lookup('env', 'KUBE_CLOUD_CONF') | b64decode }}"

rke_registration_server: "{{ hostvars[groups['controllers'][0]]['ansible_fqdn'] | default(groups['controllers'][0]) }}"
rke_setup_storage_drivers: true
