- name: Setup RKE
  hosts: rke_cluster
  roles:
    - role: rke
      tags: ["controller", "agent"]

- name: Setup cloudman
  hosts: controllers[0]
  roles:
    - role: cloudman-boot
      tags: ["cloudman"]
