- name: Create temp file for cloudman helm values
  tempfile:
    state:  file
    suffix: helmvals
  register: temp_helmvals

- name: Render CloudMan chart custom values file
  template:
    src: cm_chart_values.yml.j2
    dest: "{{ temp_helmvals.path }}"

- name: Create CloudMan namespace
  command: >
    /usr/local/bin/kubectl create namespace cloudman
  ignore_errors: true

- name: Helm install CloudMan
  command: >
    /usr/local/bin/helm upgrade --install cloudman galaxyproject/cloudman
    --force
    --namespace "{{ cm_namespace_name }}"
    {% if cm_chart_version %}
    --version "{{ cm_chart_version }}"
    {% endif %}
    -f "{{ temp_helmvals.path }}"
  ignore_errors: true

- name: Remove temporary values file
  file:
    path: "{{ temp_helmvals.path }}"
    state: absent
  when: temp_helmvals.path is defined
