- name: Create CloudMan chart template file
  local_action: template src=cm_chart_values.yml.j2 dest=/tmp/template_cm_chart_values.j2
  become: no

- name: Render CloudMan chart custom values file
  template:
    src: /tmp/template_cm_chart_values.j2
    dest: /tmp/cm_chart_values.yml

- name: Create CloudMan namespace
  command: >
    /usr/local/bin/kubectl create namespace cloudman
  ignore_errors: true

- name: Helm install CloudMan latest
  command: >
    /usr/local/bin/helm upgrade --install cloudman galaxyproject/cloudman
    --namespace "{{ cm_namespace_name }}"
    -f /tmp/cm_chart_values.yml
  ignore_errors: true
  when: cm_chart_version == ''


- name: Helm install CloudMan
  command: >
    /usr/local/bin/helm upgrade --install cloudman galaxyproject/cloudman
    --namespace "{{ cm_namespace_name }}"
    --version "{{ cm_chart_version }}"
    -f /tmp/cm_chart_values.yml
  ignore_errors: true
  when: cm_chart_version != ''
