- name: Add wunderio Helm repo for RClone
  shell: /usr/local/bin/helm repo add wunderio https://storage.googleapis.com/charts.wdr.io/
  ignore_errors: True

- name: Add CloudVE Helm repo
  shell: /usr/local/bin/helm repo add galaxyproject {{ cm_charts_repo }}
  ignore_errors: True

- name: Update Helm repos
  shell: /usr/local/bin/helm repo update
