- name: Add stable Helm repo
  shell: /usr/local/bin/helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: Add CloudVE Helm repo
  shell: /usr/local/bin/helm repo add galaxyproject {{ cm_charts_repo }}

- name: Update Helm repos
  shell: /usr/local/bin/helm repo update
