- name: Setup system packages
  include_tasks: system.yaml
  when: not rke_in_docker

- name: Setup rke
  include_tasks: rke.yaml
  when: cm_cluster_type == 'KUBE_RKE'

- name: Setup Helm
  include_tasks: helm.yaml

- name: Setup ingress controller
  include_tasks: ingress.yaml
  when: cm_cluster_type == 'KUBE_K3S'

- name: Setup cert-manager
  include_tasks: certmanager.yaml

- name: Setup common storage providers
  include_tasks: storage.yaml

- name: Setup CloudMan
  include_tasks: cloudman.yaml
  when: cm_skip_cloudman is not defined or not (cm_skip_cloudman|bool)

- name: Wait for CloudMan
  include_tasks: finish.yaml
