- name: Create a secret for a private image registry
  command: >
    /usr/local/bin/kubectl create secret -n {{ app_namespace }} docker-registry 
    --docker-server={{ registry_server }} --docker-username={{ registry_username }}
    --docker-password={{ registry_password }} {{ registry_name }}
  ignore_errors: true

- name: Allow private images to be pulled
  command: >
    /usr/local/bin/kubectl patch sa default -n {{ app_namespace }}
    -p '"imagePullSecrets": [{"name": "{{ registry_name }}" }]'
  ignore_errors: true
