---
- name: Get the K8S env project id
  shell: rancher --url http://localhost:{{ rancher_port }} --access-key {{ api_user }} --secret-key {{ api_password }} env | grep {{ k8s_project_name }} | cut -f1 -d' '
  register: project_id

- name: Get the environment API key
  uri:
    method: POST
    status_code: 201
    url: "http://{{ rancher_server }}:{{ rancher_port }}/v2-beta/projects/{{ project_id.stdout }}/apikey"
    return_content: yes
    user: "{{ api_user }}"
    password: "{{ api_password }}"
  register: env_api_key

- name: Make sure kube conf dir exist
  file:
    path: "{{ kube_dir }}"
    state: directory

- name: Generate kubectl config
  template:
    src: kubectl_config.j2
    dest: "{{ kube_dir }}/config"
    mode: 0600
  register: kubectl_config

- name: Wait for the K8S project to become active
  uri:
    method: GET
    status_code: 200
    url: "http://{{ rancher_server }}:{{ rancher_port }}/v2-beta/projects/{{ project_id.stdout }}"
    return_content: yes
    user: "{{ api_user }}"
    password: "{{ api_password }}"
  register: project
  until: project.json.healthState == 'healthy'
  retries: 40
  delay: 15

- name: Init Helm
  environment:
    KUBECONFIG: "{{ kube_dir }}/config"
  shell: helm init
