---
- debug: msg="Using rancher pwd {{ rancher_password }}"

- name: Pull and run the Rancher/server container
  docker_container:
      name: "{{ rancher_name }}"
      image: rancher/rancher:{{ rancher_version }}
      restart_policy: unless-stopped
      ports:
        - "{{ rancher_port_80}}:80"
        - "{{ rancher_port }}:443"

- debug: msg="Using rancher_server address {{ rancher_server }}"

- name: Setup login
  uri:
    url: "https://{{ rancher_server }}:{{ rancher_port }}/v3-public/localProviders/local?action=login"
    method: POST
    body_format: json
    body:
      username: admin
      password: admin
    validate_certs: no
    status_code: 201
    return_content: yes
  ignore_errors: yes
  register: login_response
  until: login_response['status'] | default(0) == 201
  retries: 6
  delay: 10

- name: Set current admin password
  set_fact:
    rpwd: admin
    token: "{{ login_response.json.token }}"
  when: login_response is succeeded

- name: Re-setup login
  uri:
    url: "https://{{ rancher_server }}:{{ rancher_port }}/v3-public/localProviders/local?action=login"
    method: POST
    body_format: json
    body:
      username: admin
      password: "{{ rancher_password }}"
    validate_certs: no
    status_code: 201
    return_content: yes
  register: login_response
  when: login_response is failed

- name: Set current admin password
  set_fact:
    rpwd: "{{ rancher_password }}"
    token: "{{ login_response.json.token }}"
  when: rpwd is undefined

- name: Change password
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/users?action=changepassword
    method: POST
    body_format: json
    body:
      currentPassword: "{{ rpwd }}"
      newPassword: "{{ rancher_password }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no

# Not used but left in case we need it one day
# - name: Create an API key
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/token
#     method: POST
#     body_format: json
#     body:
#       type: token
#       description: cloudman-boot ansible
#       ttl: 3600000  # Expires in 1 hour
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#     status_code: 201
#   register: api_token

- name: Configure server URL
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/settings/server-url
    method: PUT
    body_format: json
    body:
      name: server-url
      type: setting
      value: "https://{{ rancher_server }}:{{ rancher_port }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no

- name: Check if cluster already exists
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters?name={{ cm_cluster_name }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: clusters

- name: Store existing cluster id
  set_fact:
    cluster_id: "{{ clusters.json.data[0].id }}"
  when: clusters.json.data | length > 0

- name: Create a cluster
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/cluster
    method: POST
    body_format: json
    body:
      type: cluster
      rancherKubernetesEngineConfig:
        ignoreDockerVersion: true
        ingress:
          provider: nginx
          type: ingressConfig
      name: "{{ cm_cluster_name }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  register: cluster
  when: clusters.json.data | length == 0

- name: Store new cluster id
  set_fact:
    cluster_id: "{{ cluster.json.id }}"
  when: cluster is not skipped

- name: Generate cluster registration token and extract node command
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusterregistrationtoken
    method: POST
    body_format: json
    body:
      type: clusterRegistrationToken
      clusterId: "{{ cluster_id }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  register: node_command

- name: Extract node command
  set_fact:
    node_command: "{{ node_command.json.nodeCommand }}"

- name: Remove sudo from the node command
  set_fact:
    node_command: "{{ node_command | replace('sudo ', '') }}"

- debug: msg="Node cmd is {{ node_command }} {{ node_command }} {{ rancher_master_etcd }} {{ rancher_master_controlplane }} {{ rancher_master_as_worker }}"

- name: Get current cluster status
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters/{{ cluster_id }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cluster_state1

- name: Add master as a node
  command: "{{ node_command }} {{ rancher_master_etcd }} {{ rancher_master_controlplane }} {{ rancher_master_as_worker }}"
  when: cluster_state1.json.state == "provisioning"

- name: Wait for the cluster to become active
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters/{{ cluster_id }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cluster_state_dbg

- name: Wait for the cluster to become active
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters/{{ cluster_id }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cluster_state2
  until: '"active" in cluster_state2.json.state'
  retries: 100
  delay: 15

- name: Add persistent volumes
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port}}/v3/clusters/{{ cluster_id }}/persistentvolume
    method: POST
    body_format: json
    body:
      type: persistentVolume
      name: "{{ item.name }}"
      capacity:
        storage: "{{ item.capacity }}"
      hostPath:
        type: hostPathVolumeSource
        path: "{{ item.path }}"
        kind: "{{ item.kind }}"
      accessModes: "{{ item.accessModes }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  with_items:
    - {'name': 'cm-volume', 'capacity': '10Gi', 'path': '/psql_volume', 'kind': 'DirectoryOrCreate', 'accessModes': ['ReadWriteOnce', 'ReadWriteMany']}
#     - {'name': 'galaxy-volume', 'capacity': '20Gi', 'path': '/galaxy_volume', 'kind': 'DirectoryOrCreate', 'accessModes': ['ReadWriteMany']}
  ignore_errors: true

- name: Check if cloudman app is in the catalog already
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/catalogs?name={{ cm_catalog_name }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cm_helm_app

- name: Add custom Helm repos to the Rancher catalog
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/catalog
    method: POST
    body_format: json
    body:
      branch: "{{ item.branch }}"
      kind: helm
      name: "{{ item.app_name }}"
      type: catalog
      url: "{{ item.app_url }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  when: cm_helm_app.json.data | length == 0
  with_items:
    - { app_name: "{{ galaxy_catalog_name }}", app_url: 'https://github.com/CloudVE/helm-charts.git', branch: 'master' }
  loop_control:  # Rancher's concurrency here does not keep up without sleep
    pause: 10

- name: Get project info
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/projects?clusterId={{ cluster_id }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: project

- name: Set project id
  set_fact:
    project_id: "{{ project.json.data[0].id }}"

- name: Check if CloudMan namespace already exists
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/cluster/{{ cluster_id }}/namespaces?name={{ cm_namespace_name }}
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cm_ns

- name: Add CloudMan namespace
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters/{{ cluster_id }}/namespace
    method: POST
    body_format: json
    body:
      name: "{{ cm_namespace_name }}"
      type: namespace
      projectId: "{{ project_id }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  when: cm_ns.json.data | length == 0

# - name: Check if nfs-provisioner app has been added
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/project/{{ project_id }}/apps?name=nfs-provisioner
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#   register: nfs_app

# - name: Add nfs-provisioner app
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/projects/{{ project_id }}/app
#     method: POST
#     body_format: json
#     body:
#       name: nfs-provisioner
#       targetNamespace: "{{ cm_namespace_name }}"
#       type: app
#       prune: false
#       projectId: "{{ project_id }}"
#       externalId: "catalog://?catalog=library&template=nfs-provisioner&version=0.1.0"
#       answers:
#         defaultImage: "true"
#         image.repository: "quay.io/kubernetes_incubator/nfs-provisioner"
#         image.tag: "v1.0.8"
#         nfs.hostPort: "2049"
#         persistence.defaultClass: "true"
#         persistence.hostPath: "/srv"
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#     status_code: 201
#   when: nfs_app.json.data | length == 0

- name: Check if CloudMan app has been added
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/project/{{ project_id }}/apps?name=cloudman
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
  register: cm_app

- name: Launch CloudMan app
  uri:
    url: https://{{ rancher_server }}:{{ rancher_port }}/v3/projects/{{ project_id }}/app
    method: POST
    body_format: json
    body:
      name: cloudman
      targetNamespace: "{{ cm_namespace_name }}"
      type: app
      prune: false
      projectId: "{{ project_id }}"
      externalId: "catalog://?catalog={{ galaxy_catalog_name }}&template=cloudman&version={{ cm_helm_version }}"
      answers:
        cloudlaunch.cloudlaunch-server.extra_env.rancher_url: "https://{{ rancher_server }}:{{ rancher_port }}"
        cloudlaunch.cloudlaunch-server.extra_env.rancher_api_key: "{{ token }}"
        cloudlaunch.cloudlaunch-server.extra_env.rancher_cluster_id: "{{ cluster_id }}"
        cloudlaunch.cloudlaunch-server.extra_env.rancher_project_id: "{{ project_id }}"
        cloudlaunch.cloudlaunch-server.extra_env.rancher_node_command: "{{ node_command }} --worker"
        cloudlaunch.cloudlaunch-server.extra_env.cm_bootstrap_data: "{{ cm_bootstrap_data|default('') }}"
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: no
    status_code: 201
  when: cm_app.json.data | length == 0

# - name: Check if Galaxy namespace already exists
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/cluster/{{ cluster_id }}/namespaces?name={{ galaxy_namespace_name }}
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#   register: gxy_ns

# - name: Add Galaxy namespace
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/clusters/{{ cluster_id }}/namespace
#     method: POST
#     body_format: json
#     body:
#       name: "{{ galaxy_namespace_name }}"
#       type: namespace
#       projectId: "{{ project_id }}"
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#     status_code: 201
#   when: gxy_ns.json.data | length == 0

# - name: Check if Galaxy app has been added
#   uri:
#     url: "https://{{ rancher_server }}:{{ rancher_port }}/v3/project/{{ project_id }}/apps?name={{ galaxy_chart_name }}"
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#   register: gxy_app

# - name: Launch Galaxy app
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/projects/{{ project_id }}/app
#     method: POST
#     body_format: json
#     body:
#       name: galaxy
#       targetNamespace: "{{ galaxy_namespace_name }}"
#       type: app
#       prune: false
#       projectId: "{{ project_id }}"
#       externalId: "catalog://?catalog={{ galaxy_catalog_name }}&template={{ galaxy_chart_name }}&version={{ galaxy_helm_version }}"
#       answers:
#         admin.email: "admin@galaxyproject.org"
#         admin.password: "{{ rancher_password }}"
#         admin.username: "admin"
#         ingress.path: "/galaxy"
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no
#     status_code: 201
#   when: gxy_app.json.data | length == 0

# - name: Disable the default library catalog
#   uri:
#     url: https://{{ rancher_server }}:{{ rancher_port }}/v3/catalogs/library
#     method: DELETE
#     headers:
#       Authorization: Bearer {{ token }}
#     validate_certs: no

- name: Print Rancher's URL
  debug:
    msg: "You can connect to rancher server https://{{ rancher_server }}:{{ rancher_port }}"
