---
- name: Pull and run the Rancher/server contianer
  docker_container:
      name: "{{ rancher_name }}"
      image: rancher/server:{{ rancher_version }}
      restart_policy: always
      ports:
        - "{{ rancher_port }}:8080"

- name: Wait for the Rancher server to start
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10

- name: Download kubectl script
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.5.4/bin/linux/amd64/kubectl
    dest: /usr/local/bin
    mode: 0755

- name: Fetch rancher CLI
  unarchive:
    src: https://github.com/rancher/cli/releases/download/v0.6.1/rancher-linux-amd64-v0.6.1.tar.gz
    dest: /tmp
    remote_src: True

- name: Place rancher CLI
  copy:
    src: /tmp/rancher-v0.6.1/rancher
    dest: /usr/local/bin
    mode: 0755
    remote_src: True

- name: Check if env already exists
  shell: rancher --url http://localhost:8080 env | grep CMk8s
  register: env
  failed_when: "env.rc == 2"

- name: Add a env
  shell: rancher --url http://localhost:8080 env create -t kubernetes CMk8s
  when: "env.rc == 1"

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ ansible_ssh_host }}:{{ rancher_port }}"
