---
- name: Install httplib2
  pip:
    name: httplib2
    state: latest

- name: Return the registration token URL of Rancher server
  uri:
    method: POST
    status_code: 201
    # FIXME: Using locahost here instead of rancher_server does not work
    # because "Register Rancher server as a host" task fails. Rancher requires
    # its hosts to have a public IP and the output of this task defined the URL
    # of the hast add task.
    url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ project_id.stdout }}"
    return_content: yes
    user: "{{ api_user }}"
    password: "{{ api_password }}"
  register: rancher_token_url

- name: Return the registration URL of Rancher server
  uri:
    method: GET
    url: "{{ rancher_token_url.json['links']['self'] }}"
    return_content: yes
    user: "{{ api_user }}"
    password: "{{ api_password }}"
  register: rancher_token

- debug:
    msg: "rancher_token_url: {{ rancher_token_url }}   ---  {{ rancher_token.json['registrationUrl'] }}"

- name: Check if the rancher-agent is running
  command: docker ps -a
  register: containers

- name: Register Rancher server as a host
  docker_container:
      name: "{{ rancher_name }}Host"
      image: "{{ rancher_token.json['image'] }}"
      privileged: yes
      detach: True
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/rancher:/var/lib/rancher
      command: "{{ rancher_token.json['registrationUrl'] }}"
      state: started
  when: "{{ 'rancher-agent' not in containers.stdout }}"
