---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: docker-redhat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- import_tasks: docker-debian.yml
  when: ansible_os_family == 'Debian'
  static: no

- name: Create a docker group
  group:
      name=docker
      state=present

- name: Add user(s) to docker group
  user:
      name={{ item }}
      groups=docker
      state=present
      append=yes
  with_items: "{{ docker_users }}"
  when: docker_users is defined

- name: Configure Docker
  template:
      src=default_docker.j2
      dest=/etc/default/docker
      mode=0644
      owner=root
      group=root
  notify: restart docker

- name: Make sure git is installed
  package:
    name: git
    state: latest
